const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(require('os').tmpdir(),'cineverse-home-fix');fs.mkdirSync(out,{recursive:true});
const fixture=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/app-state-v2.json'),'utf8'));
(async()=>{const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);try{if(!f.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({channel:'msedge',headless:true});const results=[];
try{for(const populated of [false,true]){const seed=structuredClone(fixture);seed.movies=Array.from({length:4},(_,i)=>{const m=structuredClone(fixture.movies[0]);m.id='test-'+i;m.info.title='A long film title for layout testing '+i;m.info.overview='A detailed description of the film and its characters. '.repeat(12);m.watchHistory=[{date:populated?'2026-10-02':'2026-09-02',rating:9}];m.plans=populated?[{month:'2026-10',status:'planned',plannedDate:'2026-10-12'}]:[];return m});const want=structuredClone(seed.movies[0]);want.id='want-test';want.personal.status='want';want.personal.want=true;want.watchHistory=[];want.plans=[];seed.movies.push(want);seed.settings.themePreset='snow';if(!populated)seed.home.radar=[];else seed.home.radar.forEach(x=>x.discoveredAt='2026-10-02');
const ctx=await browser.newContext({serviceWorkers:'block'});await ctx.addInitScript(seed=>{const D=Date;window.Date=class extends D{constructor(...args){super(...(args.length?args:['2026-10-04T12:00:00+08:00']))}static now(){return D.parse('2026-10-04T12:00:00+08:00')}};localStorage.setItem('movie-collection-v2',JSON.stringify(seed))},seed);const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{if(r.request().url().startsWith(base))return r.continue();if(r.request().resourceType()==='script')return r.fulfill({contentType:'text/javascript',body:r.request().url().includes('supabase')?'window.supabase={createClient:()=>({auth:{onAuthStateChange(){return {data:{subscription:{unsubscribe(){}}}}},async getSession(){return {data:{session:null}}}}})};':''});return r.fulfill({contentType:'application/json',body:'{}'})});
for(const [width,height] of [[1440,900],[1920,1080],[3840,2160],[390,844]]){await page.setViewportSize({width,height});await page.goto(base+'/index.html#home',{waitUntil:'networkidle'});await page.waitForTimeout(350);const data=await page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom}};const panels=[...document.querySelectorAll('#homeView .home-triple>.panel')].map(rect);const rows=[...document.querySelectorAll('#recentGrid .recent')].map(rect);const el=document.querySelector('#monthTopWorkV3');return {panels,rows,empty:el.classList.contains('is-empty'),month:rect(el),overflow:document.documentElement.scrollWidth>innerWidth+1,clipped:[...document.querySelectorAll('#recentGrid .t,#recentGrid .recent-metric,#homeView .random-main')].filter(e=>e.scrollWidth>e.clientWidth+1).length,areas:getComputedStyle(document.querySelector('.home-triple')).gridTemplateAreas,poster:rect(document.querySelector('#monthTopPosterV3'))}});results.push({width,populated,...data,errors});assert(!data.overflow,'page overflow '+width);assert(data.clipped===0,'clipped text');assert(data.rows.length===4,'four rows');assert(data.rows.every((r,i)=>!i||r.y>=data.rows[i-1].bottom-1),'vertical rows');for(let i=0;i<data.panels.length;i++)for(let j=i+1;j<data.panels.length;j++){const a=data.panels[i],b=data.panels[j];assert(a.right<=b.x+1||b.right<=a.x+1||a.bottom<=b.y+1||b.bottom<=a.y+1,'overlap')};assert(data.empty===!populated,'correct month state');if(!populated)assert(data.month.h<200,'compact empty');else assert(data.poster.w<=120.1,'bounded poster');assert(!errors.length,errors.join('\n'));if(width===3840||width===390)await page.screenshot({path:path.join(out,`${populated?'full':'empty'}-${width}.png`),fullPage:true});}
await ctx.close();}console.log('PASS: 8 home layout scenarios');}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
