import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const cards = readFileSync('library-card-system-v1.js', 'utf8');
const main = readFileSync('app-main-v1.js', 'utf8');
const runtime = readFileSync('content-center-runtime-v1.js', 'utf8');
const css = readFileSync('library-card-system-v2.css', 'utf8');
assert.doesNotMatch(cards, /style\.textContent/);
assert.doesNotMatch(cards, /function decorateActions/);
assert.doesNotMatch(cards, /proxy\.hidden/);
assert.match(main, /data-library-delete/);
assert.match(main, /CineverseLibraryActions\.openWatch/);
assert.match(runtime, /library-card-system-v2\.css\?v=20260909-b02/);
assert.match(runtime, /library-card-system-v1\.js\?v=20260909-b02/);
assert.match(css, /--card-surface/);
assert.match(css, /#libraryGrid \.lib-actions/);
assert.doesNotMatch(css, /!important/);
